version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: files
      POSTGRES_PASSWORD: mysecretpw
      POSTGRES_DB: files
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      # DB
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      # AWS
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      # MISC
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3002}:80"
    environment:
      REACT_APP_API_URL: http://backend:${BACKEND_PORT:-3000}
      REACT_APP_S3_BUCKET_URL: https://${AWS_BUCKET_NAME}.s3.${AWS_REGION}.amazonaws.com/
